management.endpoints.web.exposure.include=*

server.port=8443
spring.data.mongodb.uri=mongodb://mongo:mongo@mongo:27017/admin

management.endpoints.web.exposure.include=prometheus
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics

#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#logging.file.name=jump-app-springboot.log

